### ISSUE TITLE
Add boost liecense to all files

### ISSUE THREAD

**Issue by diehlpk** [AALEKH/hpxflow#14]
# Copyright (c) 2016 you name
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

**Comment by diehlpk** [comment]
CMakeLists.txt is missing.

**Comment by AALEKH** [comment]
Fixed by : https://github.com/AALEKH/hpxflow/commit/8d55555ae8725d7b0bdad808edeee353339985c8
